### PR TITLE
feat(): previews template customization

### PR DESCRIPTION
**Pull request by locinus**
Hello !
Ok, a new PR for this feature, on the right branch and with the example as an experimental feature "F3".

I have also written 2 unit tests for the previews component; they use intermediary components that build a template (as an easy way to get TemplateRef to give as the appropriate PreviewsComponent input). One uses a totally "different" template. The other one uses the "default" template. Each test checks that the proper HTML elements are present.

A couple questions!
- I used example id 902 for this new example. Within openModal(), I didn't add yet another optional parameters to provide a templateRef, but has based it directly on the 902 id. Optional parameter/magic number, what's your choice here?
- If you will, I'd like to propose a description on how to use the previews customization, like on a new left item here (https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/features), but where could I do that? It appears this page is not part of this repo?

Also, 2 hmm... almost related things:
- what do you think of adding a 'cursor: pointer' css to the preview images (and actually to the whole preview container I set up, which reacts to (click) and (keyup)) ?
- about the initial need for preview customization, I've noted this:
_Ultimately, I'd like to use picture-specific information which (if I'm not wrong) can not fit anywhere in the ModalImage object, such as the picture date for instance. So to fully be able to do so, an evolution to add a custom Object in ModalImage, which data could be used in template customizations, would be necessary, so that's to be discussed._
What's your thought about that?

Be well !

### CODE REVIEW

**Comment by Ks89** [comment]
First of all thank you for the PR and sorry for my delay.
I add some comments quoting your description.


> Ok, a new PR for this feature, on the right branch and with the example as an experimental feature "F3".

Good


> I have also written 2 unit tests for the previews component; they use intermediary components that build a template (as an easy way to get TemplateRef to give as the appropriate PreviewsComponent input). One uses a totally "different" template. The other one uses the "default" template. Each test checks that the proper HTML elements are present.

Really appreciated 👍 


> I used example id 902 for this new example. Within openModal(), I didn't add yet another optional parameters to provide a templateRef, but has based it directly on the 902 id. Optional parameter/magic number, what's your choice here?

I suggest to write a custom method only for this example to keep all others easier to understand. For example something like this:

```
  openModalWithPreviewsTemplate(id: number, imagesArrayToUse: Image[], imageIndex: number, libConfig?: ModalLibConfig): void {
    if(imagesArrayToUse.length === 0) {
      console.error('Cannot open modal-gallery because images array cannot be empty');
      return;
    }
    if(imageIndex > imagesArrayToUse.length - 1) {
      console.error('Cannot open modal-gallery because imageIndex must be valid');
      return;
    }
    const imageToShow: Image = imagesArrayToUse[imageIndex];
    const dialogRef: ModalGalleryRef = this.modalGalleryService.open({
      id,
      images: imagesArrayToUse,
      currentImage: imageToShow,
      libConfig,
      previewsTemplate: this.previewsTemplate,
    } as ModalGalleryConfig) as ModalGalleryRef;
  }
```


> If you will, I'd like to propose a description on how to use the previews customization, like on a new left item here (https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/features), but where could I do that? It appears this page is not part of this repo?

Very good idea. This is the doc website repo https://github.com/Ks89/angular-modal-gallery-2021-v9.github.io
Feel free to create a PR in that repo.


> what do you think of adding a 'cursor: pointer' css to the preview images (and actually to the whole preview container I set up, which reacts to (click) and (keyup)) ?

Absolutely yes, this is important for accessibility. Originally I added both of them, so It's important to preserve this behaviour.


> Ultimately, I'd like to use picture-specific information which (if I'm not wrong) can not fit anywhere in the ModalImage object, such as the picture date for instance. So to fully be able to do so, an evolution to add a custom Object in ModalImage, which data could be used in template customizations, would be necessary, so that's to be discussed.
What's your thought about that?

Yes you are right, but probably it's better to finish and merge this PR to release 9.1.0 and then work on that feature in a new PR. This will keep this PR smaller and we can release a new version of the library faster.
Also, we should discuss how to add that info to the ModalImage object. We need a trade off between a generic object of type any and something structured but more stricter.

**Comment by locinus** [comment]
Hi there!

> I suggest to write a custom method only for this example to keep all others easier to understand.

Created a new method as you suggested (I'd totally missed the fact several of these methods existed).

> Absolutely yes, this is important for accessibility. Originally I added both of them, so It's important to preserve this behaviour.

Behaviour back on track! Sorry for the mistake.
Now there's a new distinct class **preview-container**, in between **preview-containers** and **preview-image**. This new class handles the lateral margin and the cursor look upon the preview container.

> Very good idea. This is the doc website repo https://github.com/Ks89/angular-modal-gallery-2021-v9.github.io Feel free to create a PR in that repo.

Perfect. I'll have a look at it.

> Yes you are right, but probably it's better to finish and merge this PR to release 9.1.0 and then work on that feature in a new PR. This will keep this PR smaller and we can release a new version of the library faster. Also, we should discuss how to add that info to the ModalImage object. We need a trade off between a generic object of type any and something structured but more stricter.

Sure thing for the release. I was mentioning that point only to progress on the reflection about it.
In the meantime, I believe that as a user it's possible to tweak the passed ModalImages or even to create an interface extending it, to fill extra information in. I'll check that on my side after the 9.1.0 release and let you know!

**Comment by locinus** [comment]
Hi there! Just a heads-up.
I'll create a new PR for the little things I was mentionning [here](https://github.com/Ks89/angular-modal-gallery/issues/253#issuecomment-1091703011), because it will involve several changes, and it'd be better to keep things separated. So if you think this PR #254 is fine, feel free to merge it!

**Comment by Ks89** [comment]
Ok Thanks. Give a couple of days to test it.

**Comment by Ks89** [comment]
@locinus merged and released as 9.1.0-beta.1
I also updated official examples in /examples folder and tested with angular universal.

Please, can you try the new bundled version with `npm i @ks89/angular-modal-gallery@beta`?
When you'll be ready, please create the PR also on https://github.com/Ks89/angular-modal-gallery-2021-v9.github.io with the doc and a live example.
If everything will be ok, we can release it as 9.1.0 (as stable).

**Pull request merged**
