### PR TITLE
Wrong "Prev" button title for legacy mode

### PR DESCRIPTION
**Pull request by aslubsky**

### CODE REVIEW

**Comment by Ks89** [comment]
Thank you for your pr. I'll check it in some days.

**Comment by Ks89** [comment]
merged on master

**Comment by Ks89** [comment]
Damn, I cannot build master branch with macOS Catalina. I'm receiving weird errors.

Do you need this fix in v.7.x.x or could you wait for 8.0.0?

**Comment by aslubsky** [comment]
> Damn, I cannot build master branch with macOS Catalina. I'm receiving weird errors.
> 
> Do you need this fix in v.7.x.x or could you wait for 8.0.0?

Sure

**Comment by Ks89** [comment]
"Sure" is about version 8.0.0 or 7.x.x? :)

**Comment by aslubsky** [comment]
8.0.0

**Pull request merged**
